services:
  - type: web
    name: qr-capacitaciones
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: JWT_SIGNING_KEY
        generateValue: true
      - key: QR_SIGNING_KEY
        generateValue: true
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "1"
      - key: SEED_ON_START
        value: "1"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        value: "admin12345"
      - key: DATABASE_URL
        fromDatabase:
          name: qr-capacitaciones-db
          property: connectionString

databases:
  - name: qr-capacitaciones-db
    plan: starter
    databaseName: capacitaciones
    user: capacitaciones
